config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'login' => 'sessions#destroy'

  resources :users, except: [:index, :new] do
    resources :jobs do
      resources :notes
    end
  end

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user
  has_many :notes, dependent: :destroy
  validates :company_name, :presence => true
  default_scope -> { order(updated_at: :asc) }
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :job
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :jobs, dependent: :destroy
  before_save { email.downcase! }
  before_save { fname.capitalize! }
  before_save { lname.capitalize! }
  validates :fname,  presence: true, length: { maximum: 25 }
  validates :lname,  presence: true, length: { maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @user = current_user
    @jobs = @user.jobs
  end

  def new
    @user = current_user
    @job = @user.jobs.build
  end

  def create
    @user = current_user
    @job = @user.jobs.build(job_params)
    if @job.save
      flash[:success] = "Job record created!"
      redirect_to user_jobs_path @user
    else
      render 'new'
    end
  end

  def show
    @user = current_user
    @job = @user.jobs.find(params[:id])
    @applied = 'No'
    if @job.applied
      @applied = 'Yes'
    end
  end

  def edit
    @user = current_user
    @job = @user.jobs.find(params[:id])
  end

  def update
    @user = current_user
    @job = @user.jobs.find(params[:id])
    if @job.update_attributes(job_params)
      flash[:success] = "Job record updated!"
      redirect_to user_jobs_path @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = current_user
    @job = @user.jobs.find(params[:id]).destroy
    flash[:success] = "Job record successfully destroyed."
    redirect_to user_jobs_path @user
  end

  private
    def job_params
      params.require(:job).permit( :company_name, :location, :role, :source, :contact_name, :contact_email,
                                    :contact_phone, :applied, :date_applied)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user_jobs_path user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Registration successful! Welcome to App.ly!"
      log_in @user
      redirect_to user_path @user
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:fname, :lname, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Return full title on a per-page basis
  def full_title(page_title = '')
    base_title = "App.ly - The documenting tool for every job seeker"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/_form_job.html.erb
<% provide(:title, "Create Job Record") %>
<%= form_for [@user, @job], :html => {:class => "ui form error"} do |f| %>
  <div class="field required">
    <%= f.label :company_name %>
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :role %>
    <%= f.text_field :role %>
  </div>
  <div class="field">
    <%= f.label :source %>
    <%= f.text_field :source %>
  </div>
  <div class="fields">
    <div class="field">
      <%= f.label :contact_name %>
      <%= f.text_field :contact_name %>
    </div>
    <div class="field">
      <%= f.label :contact_email %>
      <%= f.text_field :contact_email %>
    </div>
    <div class="field">
      <%= f.label :contact_phone %>
      <%= f.text_field :contact_phone %>
    </div>
  </div>
  <div class="fields">
    <div class="field">
      <%= f.label :applied %>
      <%= f.check_box :applied %>
    </div>
    <div class="field">
      <%= f.label :date_applied %>
      <%= f.date_field :date_applied %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "Save Job Record", class: "ui fluid green button" %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<% provide :title, "Edit" %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Edit Job Record</h1>
    <%= render 'form_job' %>
  </div>
</div>

app/views/jobs/index.html.erb
<h2 class="ui dividing header">Job Dashboard</h2>
<%= link_to raw('<button class="ui button"><i class="fa fa-plus fa-lg"></i></button>'), new_user_job_path(current_user, @job) %>
<% @jobs.in_groups_of(4, false).each do |group| %>
<div class="row">
  <% group.each do |job| %>
  <div class="col-sm-12 col-md-3">
    <div class="ui link cards">
      <div class="card">
        <div class="content">
          <div class="ui icon buttons right floated ">
            <%= link_to raw('<button class="ui button action"><i class="fa fa-eye"></i></button>'), user_job_path(current_user, job) %>
            <%= link_to raw('<button class="ui button action"><i class="fa fa-edit"></i></button>'), edit_user_job_path(current_user, job) %>
            <%= link_to raw('<button class="ui button action"><i class="fa fa-remove"></i></button>'), user_job_path(current_user, job), method: :delete, data: { confirm: 'Are you sure?' }%>
          </div>
          <div class="header">
            <%= job.company_name  %>
          </div>
          <div class="meta">
            <%= job.role %>
          </div>
          <% if job.source %>
          <div class="description">
            <%= link_to "Original Source", job.source, :target => "_blank" %>
          </div>
          <% end %>
        </div>
        <div id="add-note" class="extra content">
          <div class="ui small transparent left icon input">
            <i class="write icon"></i>
            <input placeholder="Add Note ..." type="text_area">
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
<% end %>

app/views/jobs/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Create Job Record</h1>
    <%= render 'form_job' %>
  </div>
</div>

app/views/jobs/show.html.erb
<h1 class="ui dividing header">Job Details</h1>
<h2><%= @job.company_name %></h2>
<ul class="list-unstyled">
  <li><strong>Location:</strong> <%= @job.location %></li>
  <li><strong>Role:</strong> <%= @job.role %></li>
  <li><strong>Source:</strong> <%= link_to "Original Source", @job.source, :target => "_blank" %></li>
  <li><strong>Contact:</strong> <%= @job.contact_name %></li>
  <li><strong>Email:</strong> <%= @job.contact_email %></li>
  <li><strong>Phone:</strong> <%= @job.contact_phone %></li>
  <li><strong>Applied:</strong> <%= @applied %></li>
  <li><strong>Date Applied:</strong> <%= @job.date_applied %></li>
</ul>

<ul class="list-unstyled">
  <% if @job.notes %>
  <li>
    <% @job.notes.each do |note| %>
      <%= note.content %>
    <% end %>
  </li>
  <% end %>
</ul>
<div class="row">
<%= form_for [current_user,@job, Note.new], :html => {:class => "ui form error col-md-4"} do |f| %>
  <div class="field">
    <%= f.label :content, "Add Note" %>
    <%= f.text_area :content, class: "form-control" %>
  </div>
<% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="text-center">
      <small>
        App.ly | &copy; Copyright <%= Time.now.year %>
      </small>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button aria-expanded="false" class="navbar-toggle collapsed" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <% if !logged_in? %>
          <%= link_to raw('<i class="fa fa-paper-plane"></i>App.ly'), root_path, id: "logo", class: "navbar-brand" %>
          <% else %>
          <%= link_to raw('<i class="fa fa-paper-plane"></i>App.ly'), user_jobs_path(current_user), id: "logo", class: "navbar-brand" %>
          <% end %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                Account
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to 'Logout', login_path, method: :delete, data: {confirm: 'Are you sure?'} %>
                </li>
              </ul>
            </li>
            <% else %>
            <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </div>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %> </title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div class="container">
        <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <!--%=# debug(params) if Rails.env.development? %-->
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation" class="ui error message">
    <h3>Uh oh! Please address the following to save/update your account:</h3>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide :title, "Home" %>
<div class="jumbotron text-center">
  <i id="document" class="fa fa-file-text-o fa-4x"></i>
  <h1 class="ui header">Sayonara spreadsheets.</h1>
  <h2 class="ui header">The
    <strong><span class="tagline-em">better</span></strong>
    way to document your job search.</h2>
  <%= link_to raw('<p class="ui green button large">Sign Up</p>'), signup_path %>
</div>

app/views/users/_form_user.html.erb
<% provide(:title, "Signup") %>
<%= form_for @user, :html => {:class => "ui form error"} do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="two fields">
    <div class="field required">
      <%= f.label :fname, "First Name" %>
      <%= f.text_field :fname %>
    </div>
    <div class="field required">
      <%= f.label :lname, "Last Name" %>
      <%= f.text_field :lname %>
    </div>
  </div>
  <div class="field required">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="two fields">
    <div class="field required">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class="field required">
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "Sign up", class: "ui fluid green button" %>
  </div>
  <p><strong>Already have an account?</strong> <%= link_to 'Login', login_path %></p>
<% end %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Create Account</h1>
    <%= render 'form_user' %>
  </div>
</div>

app/views/users/show.html.erb
<h2 class="ui dividing header">My Account</h2>
<div class="row">
  <div class="col-sm-12 col-md-3">
    <ul class="list-unstyled">
    <li><strong>Name:</strong> <%= @user.fname %> <%= @user.lname %></li>
    <li><strong>Email:</strong> <%= @user.email %></li>
    </ul>
  </div>
</div>